'use strict';

// ═══════════════════════════════════════════════════════════════════
// NeoBasic Raylib Module — JavaScript Implementation (Stub)
// WASM binary and full wrappers will be generated by build.sh
// ═══════════════════════════════════════════════════════════════════

// This is a placeholder. The real implementation will:
// 1. Decode an embedded base64 WASM binary
// 2. Instantiate the WASM module
// 3. Provide wrapper functions for all raylib calls

const NOT_IMPLEMENTED = () => { throw new Error('raylib WASM not yet built — run neo_mods/raylib/build/build.sh'); };

// ── Color constants ───────────────────────────────────────────────

function lightgray() { return { r: 200, g: 200, b: 200, a: 255 }; }
function gray()      { return { r: 130, g: 130, b: 130, a: 255 }; }
function darkgray()  { return { r: 80,  g: 80,  b: 80,  a: 255 }; }
function yellow()    { return { r: 253, g: 249, b: 0,   a: 255 }; }
function gold()      { return { r: 255, g: 203, b: 0,   a: 255 }; }
function orange()    { return { r: 255, g: 161, b: 0,   a: 255 }; }
function pink()      { return { r: 255, g: 109, b: 194, a: 255 }; }
function red()       { return { r: 230, g: 41,  b: 55,  a: 255 }; }
function maroon()    { return { r: 190, g: 33,  b: 55,  a: 255 }; }
function green()     { return { r: 0,   g: 228, b: 48,  a: 255 }; }
function lime()      { return { r: 0,   g: 158, b: 47,  a: 255 }; }
function darkgreen() { return { r: 0,   g: 117, b: 44,  a: 255 }; }
function skyblue()   { return { r: 102, g: 191, b: 255, a: 255 }; }
function blue()      { return { r: 0,   g: 121, b: 241, a: 255 }; }
function darkblue()  { return { r: 0,   g: 82,  b: 172, a: 255 }; }
function purple()    { return { r: 200, g: 122, b: 255, a: 255 }; }
function violet()    { return { r: 135, g: 60,  b: 190, a: 255 }; }
function darkpurple(){ return { r: 112, g: 31,  b: 126, a: 255 }; }
function beige()     { return { r: 211, g: 176, b: 131, a: 255 }; }
function brown()     { return { r: 127, g: 106, b: 79,  a: 255 }; }
function darkbrown() { return { r: 76,  g: 63,  b: 47,  a: 255 }; }
function white()     { return { r: 255, g: 255, b: 255, a: 255 }; }
function black()     { return { r: 0,   g: 0,   b: 0,   a: 255 }; }
function blank()     { return { r: 0,   g: 0,   b: 0,   a: 0   }; }
function magenta()   { return { r: 255, g: 0,   b: 255, a: 255 }; }
function raywhite()  { return { r: 245, g: 245, b: 245, a: 255 }; }

// ── Stub wrappers (all functions route to NOT_IMPLEMENTED) ────────

// Window management
const initWindow = NOT_IMPLEMENTED;
const closeWindow = NOT_IMPLEMENTED;
const windowShouldClose = NOT_IMPLEMENTED;
const isWindowReady = NOT_IMPLEMENTED;
const isWindowFullscreen = NOT_IMPLEMENTED;
const isWindowHidden = NOT_IMPLEMENTED;
const isWindowMinimized = NOT_IMPLEMENTED;
const isWindowMaximized = NOT_IMPLEMENTED;
const isWindowFocused = NOT_IMPLEMENTED;
const isWindowResized = NOT_IMPLEMENTED;
const isWindowState = NOT_IMPLEMENTED;
const setWindowState = NOT_IMPLEMENTED;
const clearWindowState = NOT_IMPLEMENTED;
const toggleFullscreen = NOT_IMPLEMENTED;
const toggleBorderlessWindowed = NOT_IMPLEMENTED;
const maximizeWindow = NOT_IMPLEMENTED;
const minimizeWindow = NOT_IMPLEMENTED;
const restoreWindow = NOT_IMPLEMENTED;
const setWindowTitle = NOT_IMPLEMENTED;
const setWindowPosition = NOT_IMPLEMENTED;
const setWindowMonitor = NOT_IMPLEMENTED;
const setWindowMinSize = NOT_IMPLEMENTED;
const setWindowMaxSize = NOT_IMPLEMENTED;
const setWindowSize = NOT_IMPLEMENTED;
const setWindowOpacity = NOT_IMPLEMENTED;
const setWindowFocused = NOT_IMPLEMENTED;
const getScreenWidth = NOT_IMPLEMENTED;
const getScreenHeight = NOT_IMPLEMENTED;
const getRenderWidth = NOT_IMPLEMENTED;
const getRenderHeight = NOT_IMPLEMENTED;
const getMonitorCount = NOT_IMPLEMENTED;
const getCurrentMonitor = NOT_IMPLEMENTED;
const getMonitorWidth = NOT_IMPLEMENTED;
const getMonitorHeight = NOT_IMPLEMENTED;
const getMonitorPhysicalWidth = NOT_IMPLEMENTED;
const getMonitorPhysicalHeight = NOT_IMPLEMENTED;
const getMonitorRefreshRate = NOT_IMPLEMENTED;
const getMonitorName = NOT_IMPLEMENTED;
const setClipboardText = NOT_IMPLEMENTED;
const getClipboardText = NOT_IMPLEMENTED;
const enableEventWaiting = NOT_IMPLEMENTED;
const disableEventWaiting = NOT_IMPLEMENTED;

// Cursor
const showCursor = NOT_IMPLEMENTED;
const hideCursor = NOT_IMPLEMENTED;
const isCursorHidden = NOT_IMPLEMENTED;
const enableCursor = NOT_IMPLEMENTED;
const disableCursor = NOT_IMPLEMENTED;
const isCursorOnScreen = NOT_IMPLEMENTED;

// Drawing control
const clearBackground = NOT_IMPLEMENTED;
const beginDrawing = NOT_IMPLEMENTED;
const endDrawing = NOT_IMPLEMENTED;
const beginMode2D = NOT_IMPLEMENTED;
const endMode2D = NOT_IMPLEMENTED;
const beginMode3D = NOT_IMPLEMENTED;
const endMode3D = NOT_IMPLEMENTED;
const beginTextureMode = NOT_IMPLEMENTED;
const endTextureMode = NOT_IMPLEMENTED;
const beginShaderMode = NOT_IMPLEMENTED;
const endShaderMode = NOT_IMPLEMENTED;
const beginBlendMode = NOT_IMPLEMENTED;
const endBlendMode = NOT_IMPLEMENTED;
const beginScissorMode = NOT_IMPLEMENTED;
const endScissorMode = NOT_IMPLEMENTED;

// Timing
const setTargetFPS = NOT_IMPLEMENTED;
const getFPS = NOT_IMPLEMENTED;
const getFrameTime = NOT_IMPLEMENTED;
const getTime = NOT_IMPLEMENTED;

// Configuration
const setConfigFlags = NOT_IMPLEMENTED;
const setTraceLogLevel = NOT_IMPLEMENTED;
const takeScreenshot = NOT_IMPLEMENTED;
const openURL = NOT_IMPLEMENTED;
const setRandomSeed = NOT_IMPLEMENTED;
const getRandomValue = NOT_IMPLEMENTED;

// Input: Keyboard
const isKeyPressed = NOT_IMPLEMENTED;
const isKeyPressedRepeat = NOT_IMPLEMENTED;
const isKeyDown = NOT_IMPLEMENTED;
const isKeyReleased = NOT_IMPLEMENTED;
const isKeyUp = NOT_IMPLEMENTED;
const getKeyPressed = NOT_IMPLEMENTED;
const getCharPressed = NOT_IMPLEMENTED;

// Input: Mouse
const isMouseButtonPressed = NOT_IMPLEMENTED;
const isMouseButtonDown = NOT_IMPLEMENTED;
const isMouseButtonReleased = NOT_IMPLEMENTED;
const isMouseButtonUp = NOT_IMPLEMENTED;
const getMouseX = NOT_IMPLEMENTED;
const getMouseY = NOT_IMPLEMENTED;
const getMousePosition = NOT_IMPLEMENTED;
const getMouseDelta = NOT_IMPLEMENTED;
const setMousePosition = NOT_IMPLEMENTED;
const setMouseOffset = NOT_IMPLEMENTED;
const setMouseScale = NOT_IMPLEMENTED;
const getMouseWheelMove = NOT_IMPLEMENTED;
const getMouseWheelMoveV = NOT_IMPLEMENTED;
const setMouseCursor = NOT_IMPLEMENTED;

// Input: Gamepad
const isGamepadAvailable = NOT_IMPLEMENTED;
const getGamepadName = NOT_IMPLEMENTED;
const isGamepadButtonPressed = NOT_IMPLEMENTED;
const isGamepadButtonDown = NOT_IMPLEMENTED;
const isGamepadButtonReleased = NOT_IMPLEMENTED;
const isGamepadButtonUp = NOT_IMPLEMENTED;
const getGamepadButtonPressed = NOT_IMPLEMENTED;
const getGamepadAxisCount = NOT_IMPLEMENTED;
const getGamepadAxisMovement = NOT_IMPLEMENTED;

// Input: Touch
const getTouchX = NOT_IMPLEMENTED;
const getTouchY = NOT_IMPLEMENTED;
const getTouchPosition = NOT_IMPLEMENTED;
const getTouchPointId = NOT_IMPLEMENTED;
const getTouchPointCount = NOT_IMPLEMENTED;

// Shapes
const drawPixel = NOT_IMPLEMENTED;
const drawPixelV = NOT_IMPLEMENTED;
const drawLine = NOT_IMPLEMENTED;
const drawLineV = NOT_IMPLEMENTED;
const drawLineEx = NOT_IMPLEMENTED;
const drawLineBezier = NOT_IMPLEMENTED;
const drawCircle = NOT_IMPLEMENTED;
const drawCircleV = NOT_IMPLEMENTED;
const drawCircleLines = NOT_IMPLEMENTED;
const drawCircleLinesV = NOT_IMPLEMENTED;
const drawCircleSector = NOT_IMPLEMENTED;
const drawCircleSectorLines = NOT_IMPLEMENTED;
const drawCircleGradient = NOT_IMPLEMENTED;
const drawEllipse = NOT_IMPLEMENTED;
const drawEllipseLines = NOT_IMPLEMENTED;
const drawRing = NOT_IMPLEMENTED;
const drawRingLines = NOT_IMPLEMENTED;
const drawRectangle = NOT_IMPLEMENTED;
const drawRectangleV = NOT_IMPLEMENTED;
const drawRectangleRec = NOT_IMPLEMENTED;
const drawRectanglePro = NOT_IMPLEMENTED;
const drawRectangleGradientV = NOT_IMPLEMENTED;
const drawRectangleGradientH = NOT_IMPLEMENTED;
const drawRectangleGradientEx = NOT_IMPLEMENTED;
const drawRectangleLines = NOT_IMPLEMENTED;
const drawRectangleLinesEx = NOT_IMPLEMENTED;
const drawRectangleRounded = NOT_IMPLEMENTED;
const drawRectangleRoundedLines = NOT_IMPLEMENTED;
const drawRectangleRoundedLinesEx = NOT_IMPLEMENTED;
const drawTriangle = NOT_IMPLEMENTED;
const drawTriangleLines = NOT_IMPLEMENTED;
const drawPoly = NOT_IMPLEMENTED;
const drawPolyLines = NOT_IMPLEMENTED;
const drawPolyLinesEx = NOT_IMPLEMENTED;
const drawSplineLinear = NOT_IMPLEMENTED;
const drawSplineBasis = NOT_IMPLEMENTED;
const drawSplineCatmullRom = NOT_IMPLEMENTED;
const drawSplineBezierQuadratic = NOT_IMPLEMENTED;
const drawSplineBezierCubic = NOT_IMPLEMENTED;

// Collision (2D)
const checkCollisionRecs = NOT_IMPLEMENTED;
const checkCollisionCircles = NOT_IMPLEMENTED;
const checkCollisionCircleRec = NOT_IMPLEMENTED;
const checkCollisionPointRec = NOT_IMPLEMENTED;
const checkCollisionPointCircle = NOT_IMPLEMENTED;
const checkCollisionPointTriangle = NOT_IMPLEMENTED;
const checkCollisionPointLine = NOT_IMPLEMENTED;
const getCollisionRec = NOT_IMPLEMENTED;

// Image/Texture loading
const loadImage = NOT_IMPLEMENTED;
const loadImageRaw = NOT_IMPLEMENTED;
const loadImageSvg = NOT_IMPLEMENTED;
const loadImageFromTexture = NOT_IMPLEMENTED;
const loadImageFromScreen = NOT_IMPLEMENTED;
const isImageReady = NOT_IMPLEMENTED;
const unloadImage = NOT_IMPLEMENTED;
const exportImage = NOT_IMPLEMENTED;
const genImageColor = NOT_IMPLEMENTED;
const genImageGradientLinear = NOT_IMPLEMENTED;
const genImageGradientRadial = NOT_IMPLEMENTED;
const genImageGradientSquare = NOT_IMPLEMENTED;
const genImageChecked = NOT_IMPLEMENTED;
const genImageWhiteNoise = NOT_IMPLEMENTED;
const genImagePerlinNoise = NOT_IMPLEMENTED;
const genImageCellular = NOT_IMPLEMENTED;
const genImageText = NOT_IMPLEMENTED;

// Image manipulation
const imageCopy = NOT_IMPLEMENTED;
const imageFromImage = NOT_IMPLEMENTED;
const imageFormat = NOT_IMPLEMENTED;
const imageToPOT = NOT_IMPLEMENTED;
const imageCrop = NOT_IMPLEMENTED;
const imageAlphaCrop = NOT_IMPLEMENTED;
const imageAlphaClear = NOT_IMPLEMENTED;
const imageAlphaPremultiply = NOT_IMPLEMENTED;
const imageBlurGaussian = NOT_IMPLEMENTED;
const imageResize = NOT_IMPLEMENTED;
const imageResizeNN = NOT_IMPLEMENTED;
const imageResizeCanvas = NOT_IMPLEMENTED;
const imageMipmaps = NOT_IMPLEMENTED;
const imageDither = NOT_IMPLEMENTED;
const imageFlipVertical = NOT_IMPLEMENTED;
const imageFlipHorizontal = NOT_IMPLEMENTED;
const imageRotate = NOT_IMPLEMENTED;
const imageRotateCW = NOT_IMPLEMENTED;
const imageRotateCCW = NOT_IMPLEMENTED;
const imageColorTint = NOT_IMPLEMENTED;
const imageColorInvert = NOT_IMPLEMENTED;
const imageColorGrayscale = NOT_IMPLEMENTED;
const imageColorContrast = NOT_IMPLEMENTED;
const imageColorBrightness = NOT_IMPLEMENTED;
const imageColorReplace = NOT_IMPLEMENTED;
const imageClearBackground = NOT_IMPLEMENTED;
const imageDrawPixel = NOT_IMPLEMENTED;
const imageDrawPixelV = NOT_IMPLEMENTED;
const imageDrawLine = NOT_IMPLEMENTED;
const imageDrawLineV = NOT_IMPLEMENTED;
const imageDrawCircle = NOT_IMPLEMENTED;
const imageDrawCircleV = NOT_IMPLEMENTED;
const imageDrawCircleLines = NOT_IMPLEMENTED;
const imageDrawCircleLinesV = NOT_IMPLEMENTED;
const imageDrawRectangle = NOT_IMPLEMENTED;
const imageDrawRectangleV = NOT_IMPLEMENTED;
const imageDrawRectangleRec = NOT_IMPLEMENTED;
const imageDrawRectangleLines = NOT_IMPLEMENTED;
const imageDraw = NOT_IMPLEMENTED;
const imageDrawText = NOT_IMPLEMENTED;
const imageDrawTextEx = NOT_IMPLEMENTED;

// Texture loading
const loadTexture = NOT_IMPLEMENTED;
const loadTextureFromImage = NOT_IMPLEMENTED;
const loadTextureCubemap = NOT_IMPLEMENTED;
const loadRenderTexture = NOT_IMPLEMENTED;
const isTextureReady = NOT_IMPLEMENTED;
const unloadTexture = NOT_IMPLEMENTED;
const isRenderTextureReady = NOT_IMPLEMENTED;
const unloadRenderTexture = NOT_IMPLEMENTED;
const updateTexture = NOT_IMPLEMENTED;
const genTextureMipmaps = NOT_IMPLEMENTED;
const setTextureFilter = NOT_IMPLEMENTED;
const setTextureWrap = NOT_IMPLEMENTED;

// Texture drawing
const drawTexture = NOT_IMPLEMENTED;
const drawTextureV = NOT_IMPLEMENTED;
const drawTextureEx = NOT_IMPLEMENTED;
const drawTextureRec = NOT_IMPLEMENTED;
const drawTexturePro = NOT_IMPLEMENTED;
const drawTextureNPatch = NOT_IMPLEMENTED;

// Font loading
const getFontDefault = NOT_IMPLEMENTED;
const loadFont = NOT_IMPLEMENTED;
const loadFontEx = NOT_IMPLEMENTED;
const loadFontFromImage = NOT_IMPLEMENTED;
const isFontReady = NOT_IMPLEMENTED;
const unloadFont = NOT_IMPLEMENTED;

// Text drawing
const drawFPS = NOT_IMPLEMENTED;
const drawText = NOT_IMPLEMENTED;
const drawTextEx = NOT_IMPLEMENTED;
const drawTextPro = NOT_IMPLEMENTED;

// Text metrics
const setTextLineSpacing = NOT_IMPLEMENTED;
const measureText = NOT_IMPLEMENTED;
const measureTextEx = NOT_IMPLEMENTED;

// Text helpers
const textSubtext = NOT_IMPLEMENTED;
const textReplace = NOT_IMPLEMENTED;
const textInsert = NOT_IMPLEMENTED;
const textFindIndex = NOT_IMPLEMENTED;
const textToUpper = NOT_IMPLEMENTED;
const textToLower = NOT_IMPLEMENTED;
const textToPascal = NOT_IMPLEMENTED;
const textToInteger = NOT_IMPLEMENTED;
const textToFloat = NOT_IMPLEMENTED;

// 3D shapes
const drawLine3D = NOT_IMPLEMENTED;
const drawPoint3D = NOT_IMPLEMENTED;
const drawCircle3D = NOT_IMPLEMENTED;
const drawTriangle3D = NOT_IMPLEMENTED;
const drawCube = NOT_IMPLEMENTED;
const drawCubeV = NOT_IMPLEMENTED;
const drawCubeWires = NOT_IMPLEMENTED;
const drawCubeWiresV = NOT_IMPLEMENTED;
const drawSphere = NOT_IMPLEMENTED;
const drawSphereEx = NOT_IMPLEMENTED;
const drawSphereWires = NOT_IMPLEMENTED;
const drawCylinder = NOT_IMPLEMENTED;
const drawCylinderEx = NOT_IMPLEMENTED;
const drawCylinderWires = NOT_IMPLEMENTED;
const drawCylinderWiresEx = NOT_IMPLEMENTED;
const drawCapsule = NOT_IMPLEMENTED;
const drawCapsuleWires = NOT_IMPLEMENTED;
const drawPlane = NOT_IMPLEMENTED;
const drawRay = NOT_IMPLEMENTED;
const drawGrid = NOT_IMPLEMENTED;

// 3D model loading
const loadModel = NOT_IMPLEMENTED;
const loadModelFromMesh = NOT_IMPLEMENTED;
const isModelReady = NOT_IMPLEMENTED;
const unloadModel = NOT_IMPLEMENTED;
const getModelBoundingBox = NOT_IMPLEMENTED;

// 3D mesh generation
const genMeshPoly = NOT_IMPLEMENTED;
const genMeshPlane = NOT_IMPLEMENTED;
const genMeshCube = NOT_IMPLEMENTED;
const genMeshSphere = NOT_IMPLEMENTED;
const genMeshHemiSphere = NOT_IMPLEMENTED;
const genMeshCylinder = NOT_IMPLEMENTED;
const genMeshCone = NOT_IMPLEMENTED;
const genMeshTorus = NOT_IMPLEMENTED;
const genMeshKnot = NOT_IMPLEMENTED;
const unloadMesh = NOT_IMPLEMENTED;
const exportMesh = NOT_IMPLEMENTED;
const getMeshBoundingBox = NOT_IMPLEMENTED;
const genMeshTangents = NOT_IMPLEMENTED;

// Materials
const loadMaterialDefault = NOT_IMPLEMENTED;
const isMaterialReady = NOT_IMPLEMENTED;
const unloadMaterial = NOT_IMPLEMENTED;
const setMaterialTexture = NOT_IMPLEMENTED;
const setModelMeshMaterial = NOT_IMPLEMENTED;

// Model animation
const updateModelAnimation = NOT_IMPLEMENTED;
const unloadModelAnimation = NOT_IMPLEMENTED;
const isModelAnimationValid = NOT_IMPLEMENTED;

// 3D collision
const checkCollisionSpheres = NOT_IMPLEMENTED;
const checkCollisionBoxes = NOT_IMPLEMENTED;
const checkCollisionBoxSphere = NOT_IMPLEMENTED;
const getRayCollisionSphere = NOT_IMPLEMENTED;
const getRayCollisionBox = NOT_IMPLEMENTED;
const getRayCollisionMesh = NOT_IMPLEMENTED;
const getRayCollisionTriangle = NOT_IMPLEMENTED;
const getRayCollisionQuad = NOT_IMPLEMENTED;

// Audio device
const initAudioDevice = NOT_IMPLEMENTED;
const closeAudioDevice = NOT_IMPLEMENTED;
const isAudioDeviceReady = NOT_IMPLEMENTED;
const setMasterVolume = NOT_IMPLEMENTED;
const getMasterVolume = NOT_IMPLEMENTED;

// Sound
const loadWave = NOT_IMPLEMENTED;
const isWaveReady = NOT_IMPLEMENTED;
const loadSound = NOT_IMPLEMENTED;
const loadSoundFromWave = NOT_IMPLEMENTED;
const loadSoundAlias = NOT_IMPLEMENTED;
const isSoundReady = NOT_IMPLEMENTED;
const unloadWave = NOT_IMPLEMENTED;
const unloadSound = NOT_IMPLEMENTED;
const unloadSoundAlias = NOT_IMPLEMENTED;
const exportWave = NOT_IMPLEMENTED;
const playSound = NOT_IMPLEMENTED;
const stopSound = NOT_IMPLEMENTED;
const pauseSound = NOT_IMPLEMENTED;
const resumeSound = NOT_IMPLEMENTED;
const isSoundPlaying = NOT_IMPLEMENTED;
const setSoundVolume = NOT_IMPLEMENTED;
const setSoundPitch = NOT_IMPLEMENTED;
const setSoundPan = NOT_IMPLEMENTED;

// Music
const loadMusicStream = NOT_IMPLEMENTED;
const isMusicReady = NOT_IMPLEMENTED;
const unloadMusicStream = NOT_IMPLEMENTED;
const playMusicStream = NOT_IMPLEMENTED;
const isMusicStreamPlaying = NOT_IMPLEMENTED;
const updateMusicStream = NOT_IMPLEMENTED;
const stopMusicStream = NOT_IMPLEMENTED;
const pauseMusicStream = NOT_IMPLEMENTED;
const resumeMusicStream = NOT_IMPLEMENTED;
const seekMusicStream = NOT_IMPLEMENTED;
const setMusicVolume = NOT_IMPLEMENTED;
const setMusicPitch = NOT_IMPLEMENTED;
const setMusicPan = NOT_IMPLEMENTED;
const getMusicTimeLength = NOT_IMPLEMENTED;
const getMusicTimePlayed = NOT_IMPLEMENTED;

// AudioStream
const loadAudioStream = NOT_IMPLEMENTED;
const isAudioStreamReady = NOT_IMPLEMENTED;
const unloadAudioStream = NOT_IMPLEMENTED;
const isAudioStreamProcessed = NOT_IMPLEMENTED;
const playAudioStream = NOT_IMPLEMENTED;
const pauseAudioStream = NOT_IMPLEMENTED;
const resumeAudioStream = NOT_IMPLEMENTED;
const isAudioStreamPlaying = NOT_IMPLEMENTED;
const stopAudioStream = NOT_IMPLEMENTED;
const setAudioStreamVolume = NOT_IMPLEMENTED;
const setAudioStreamPitch = NOT_IMPLEMENTED;
const setAudioStreamPan = NOT_IMPLEMENTED;

module.exports = {
  // Colors
  lightgray, gray, darkgray, yellow, gold, orange, pink, red, maroon,
  green, lime, darkgreen, skyblue, blue, darkblue, purple, violet,
  darkpurple, beige, brown, darkbrown, white, black, blank, magenta, raywhite,
  // Window
  initWindow, closeWindow, windowShouldClose, isWindowReady, isWindowFullscreen,
  isWindowHidden, isWindowMinimized, isWindowMaximized, isWindowFocused,
  isWindowResized, isWindowState, setWindowState, clearWindowState,
  toggleFullscreen, toggleBorderlessWindowed, maximizeWindow, minimizeWindow,
  restoreWindow, setWindowTitle, setWindowPosition, setWindowMonitor,
  setWindowMinSize, setWindowMaxSize, setWindowSize, setWindowOpacity,
  setWindowFocused, getScreenWidth, getScreenHeight, getRenderWidth,
  getRenderHeight, getMonitorCount, getCurrentMonitor, getMonitorWidth,
  getMonitorHeight, getMonitorPhysicalWidth, getMonitorPhysicalHeight,
  getMonitorRefreshRate, getMonitorName, setClipboardText, getClipboardText,
  enableEventWaiting, disableEventWaiting,
  // Cursor
  showCursor, hideCursor, isCursorHidden, enableCursor, disableCursor, isCursorOnScreen,
  // Drawing
  clearBackground, beginDrawing, endDrawing, beginMode2D, endMode2D,
  beginMode3D, endMode3D, beginTextureMode, endTextureMode, beginShaderMode,
  endShaderMode, beginBlendMode, endBlendMode, beginScissorMode, endScissorMode,
  // Timing
  setTargetFPS, getFPS, getFrameTime, getTime,
  // Configuration
  setConfigFlags, setTraceLogLevel, takeScreenshot, openURL, setRandomSeed, getRandomValue,
  // Keyboard
  isKeyPressed, isKeyPressedRepeat, isKeyDown, isKeyReleased, isKeyUp, getKeyPressed, getCharPressed,
  // Mouse
  isMouseButtonPressed, isMouseButtonDown, isMouseButtonReleased, isMouseButtonUp,
  getMouseX, getMouseY, getMousePosition, getMouseDelta, setMousePosition,
  setMouseOffset, setMouseScale, getMouseWheelMove, getMouseWheelMoveV, setMouseCursor,
  // Gamepad
  isGamepadAvailable, getGamepadName, isGamepadButtonPressed, isGamepadButtonDown,
  isGamepadButtonReleased, isGamepadButtonUp, getGamepadButtonPressed,
  getGamepadAxisCount, getGamepadAxisMovement,
  // Touch
  getTouchX, getTouchY, getTouchPosition, getTouchPointId, getTouchPointCount,
  // Shapes
  drawPixel, drawPixelV, drawLine, drawLineV, drawLineEx, drawLineBezier,
  drawCircle, drawCircleV, drawCircleLines, drawCircleLinesV,
  drawCircleSector, drawCircleSectorLines, drawCircleGradient,
  drawEllipse, drawEllipseLines, drawRing, drawRingLines,
  drawRectangle, drawRectangleV, drawRectangleRec, drawRectanglePro,
  drawRectangleGradientV, drawRectangleGradientH, drawRectangleGradientEx,
  drawRectangleLines, drawRectangleLinesEx, drawRectangleRounded,
  drawRectangleRoundedLines, drawRectangleRoundedLinesEx,
  drawTriangle, drawTriangleLines, drawPoly, drawPolyLines, drawPolyLinesEx,
  drawSplineLinear, drawSplineBasis, drawSplineCatmullRom,
  drawSplineBezierQuadratic, drawSplineBezierCubic,
  // Collision 2D
  checkCollisionRecs, checkCollisionCircles, checkCollisionCircleRec,
  checkCollisionPointRec, checkCollisionPointCircle, checkCollisionPointTriangle,
  checkCollisionPointLine, getCollisionRec,
  // Images
  loadImage, loadImageRaw, loadImageSvg, loadImageFromTexture, loadImageFromScreen,
  isImageReady, unloadImage, exportImage,
  genImageColor, genImageGradientLinear, genImageGradientRadial,
  genImageGradientSquare, genImageChecked, genImageWhiteNoise,
  genImagePerlinNoise, genImageCellular, genImageText,
  imageCopy, imageFromImage, imageFormat, imageToPOT, imageCrop,
  imageAlphaCrop, imageAlphaClear, imageAlphaPremultiply, imageBlurGaussian,
  imageResize, imageResizeNN, imageResizeCanvas, imageMipmaps, imageDither,
  imageFlipVertical, imageFlipHorizontal, imageRotate, imageRotateCW, imageRotateCCW,
  imageColorTint, imageColorInvert, imageColorGrayscale, imageColorContrast,
  imageColorBrightness, imageColorReplace, imageClearBackground,
  imageDrawPixel, imageDrawPixelV, imageDrawLine, imageDrawLineV,
  imageDrawCircle, imageDrawCircleV, imageDrawCircleLines, imageDrawCircleLinesV,
  imageDrawRectangle, imageDrawRectangleV, imageDrawRectangleRec, imageDrawRectangleLines,
  imageDraw, imageDrawText, imageDrawTextEx,
  // Textures
  loadTexture, loadTextureFromImage, loadTextureCubemap, loadRenderTexture,
  isTextureReady, unloadTexture, isRenderTextureReady, unloadRenderTexture,
  updateTexture, genTextureMipmaps, setTextureFilter, setTextureWrap,
  drawTexture, drawTextureV, drawTextureEx, drawTextureRec, drawTexturePro, drawTextureNPatch,
  // Fonts
  getFontDefault, loadFont, loadFontEx, loadFontFromImage, isFontReady, unloadFont,
  // Text drawing
  drawFPS, drawText, drawTextEx, drawTextPro,
  // Text metrics
  setTextLineSpacing, measureText, measureTextEx,
  // Text helpers
  textSubtext, textReplace, textInsert, textFindIndex,
  textToUpper, textToLower, textToPascal, textToInteger, textToFloat,
  // 3D shapes
  drawLine3D, drawPoint3D, drawCircle3D, drawTriangle3D,
  drawCube, drawCubeV, drawCubeWires, drawCubeWiresV,
  drawSphere, drawSphereEx, drawSphereWires,
  drawCylinder, drawCylinderEx, drawCylinderWires, drawCylinderWiresEx,
  drawCapsule, drawCapsuleWires, drawPlane, drawRay, drawGrid,
  // Models
  loadModel, loadModelFromMesh, isModelReady, unloadModel, getModelBoundingBox,
  // Mesh
  genMeshPoly, genMeshPlane, genMeshCube, genMeshSphere, genMeshHemiSphere,
  genMeshCylinder, genMeshCone, genMeshTorus, genMeshKnot,
  unloadMesh, exportMesh, getMeshBoundingBox, genMeshTangents,
  // Materials
  loadMaterialDefault, isMaterialReady, unloadMaterial, setMaterialTexture, setModelMeshMaterial,
  // Animation
  updateModelAnimation, unloadModelAnimation, isModelAnimationValid,
  // 3D collision
  checkCollisionSpheres, checkCollisionBoxes, checkCollisionBoxSphere,
  getRayCollisionSphere, getRayCollisionBox, getRayCollisionMesh,
  getRayCollisionTriangle, getRayCollisionQuad,
  // Audio
  initAudioDevice, closeAudioDevice, isAudioDeviceReady, setMasterVolume, getMasterVolume,
  loadWave, isWaveReady, loadSound, loadSoundFromWave, loadSoundAlias,
  isSoundReady, unloadWave, unloadSound, unloadSoundAlias, exportWave,
  playSound, stopSound, pauseSound, resumeSound, isSoundPlaying,
  setSoundVolume, setSoundPitch, setSoundPan,
  loadMusicStream, isMusicReady, unloadMusicStream, playMusicStream,
  isMusicStreamPlaying, updateMusicStream, stopMusicStream, pauseMusicStream,
  resumeMusicStream, seekMusicStream, setMusicVolume, setMusicPitch, setMusicPan,
  getMusicTimeLength, getMusicTimePlayed,
  loadAudioStream, isAudioStreamReady, unloadAudioStream, isAudioStreamProcessed,
  playAudioStream, pauseAudioStream, resumeAudioStream, isAudioStreamPlaying,
  stopAudioStream, setAudioStreamVolume, setAudioStreamPitch, setAudioStreamPan,
};
